services:
    threedi.onlinesince.listener:
        class: threedi\onlinesince\event\listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
        tags:
            - { name: event.listener }
