services:
    threedi.onlinesince.listener:
        class: threedi\onlinesince\event\listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
        tags:
            - { name: event.listener }

    threedi.onlinesince.admin.controller:
        class: threedi\onlinesince\controller\admin_controller
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%			

    threedi.onlinesince.controller:
        class: threedi\onlinesince\controller\main_controller
        arguments:
            - @controller.helper
            - @template
            - @user
            - @config
